backend:
  name: github
  repo: cyhinverse/profile
  branch: main
  base_url: https://etiso.me
  auth_endpoint: api/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "works"
    label: "Works"
    folder: "src/content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "writing"
    label: "Writing"
    folder: "src/content/writing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
